#!/usr/bin/env sh

target=""

find_device() {
  device=$1
  if timeout 5 dd if="$device" of=/dev/null bs=24 count=10 iflag=fullblock 2>/dev/null; then
    return 0
  else
    return 1
  fi
}

while true; do
  for device in /dev/input/by-id/*-event-kbd; do
    if find_device "$device"; then
      target="$device"
      break 2
    fi
    sleep 1
  done
  if [ -z "$target" ]; then
    sleep 2
  fi
done

echo "Target device is: $target"
