#!/bin/bash

#####################
#                   #
#      CONFIG       #
#                   #
#####################

ARCHS=("x86-64" "i686" "aarch64")
ARCH_NAMES=("x86 64-bit" "P6 Microarchitecture (32-bit)" "ARM 64-bit")

#####################
#                   #
#      CONFIG       #
#                   #
#####################

compile() {
    case $1 in
        "x86-64")
            g++ -o normal-process -march=x86-64 main.cpp logger.cpp
            ;;
        "i686")
            g++ -o normal-process -m32 main.cpp logger.cpp
            ;;
        "aarch64")
            aarch64-linux-gnu-g++ -o normal-process main.cpp logger.cpp
            ;;
        *)
            echo "Unknown architecture selected!"
            exit 1
            ;;
    esac
}

clear && printf '\e[3J'

while true; do
    echo "Choose target architecture:"
    for i in "${!ARCHS[@]}"; do
        echo "$((i + 1)). ${ARCH_NAMES[$i]} (${ARCHS[$i]})"
    done

    read -p "Enter target number: " choice

    if [[ $choice -ge 1 && $choice -le ${#ARCHS[@]} ]]; then
        ARCH=${ARCHS[$((choice - 1))]}
        echo "Selected architecture: $ARCH"
        compile "$ARCH"
        break
    else
        echo "Invalid selection."
        clear && printf '\e[3J'
    fi
done

