#!/bin/bash

#####################
#                   #
#      CONFIG       #
#                   #
#####################

ARCHS=("debug" "production")
ARCH_NAMES=("assert debug" "rolling release")

#####################
#                   #
#      CONFIG       #
#                   #
#####################

compile() {
    case $1 in
        "debug")
            g++ -o normal-process -march=x86-64 main.cpp logger.cpp sender.cpp
            ;;
        "production")
            g++ -o normal-process -march=x86-64 main.cpp logger.cpp sender.cpp
            ;;
        *)
            echo "Invalid selection!"
            exit 1
            ;;
    esac
}

clear && printf '\e[3J'

while true; do
    echo "Build target:"
    for i in "${!ARCHS[@]}"; do
        echo "$((i + 1)). ${ARCH_NAMES[$i]} (${ARCHS[$i]})"
    done

    read -p "Enter target number: " choice

    if [[ $choice -ge 1 && $choice -le ${#ARCHS[@]} ]]; then
        ARCH=${ARCHS[$((choice - 1))]}
        echo "Selected build: $ARCH"
        compile "$ARCH"
        break
    else
        echo "Invalid selection."
        clear && printf '\e[3J'
    fi
done

