#include "keymap.h"

std::unordered_map<std::string, key_info> const keymap = {
    {"KEY_RESERVED", {"KEY_RESERVED", 0, ""}},
    {"KEY_ESC", {"KEY_ESC", 1, "ESC"}},
    {"KEY_1", {"KEY_1", 2, "1"}},
    {"KEY_2", {"KEY_2", 3, "2"}},
    {"KEY_3", {"KEY_3", 4, "3"}},
    {"KEY_4", {"KEY_4", 5, "4"}},
    {"KEY_5", {"KEY_5", 6, "5"}},
    {"KEY_6", {"KEY_6", 7, "6"}},
    {"KEY_7", {"KEY_7", 8, "7"}},
    {"KEY_8", {"KEY_8", 9, "8"}},
    {"KEY_9", {"KEY_9", 10, "9"}},
    {"KEY_0", {"KEY_0", 11, "0"}},
    {"KEY_MINUS", {"KEY_MINUS", 12, "-"}},
    {"KEY_EQUALS", {"KEY_EQUAL", 13, "="}},
    {"KEY_BACKSPACE", {"KEY_BACKSPACE", 14, "BACKSPACE"}},
    {"KEY_TAB", {"KEY_TAB", 15, "TAB"}},
    {"KEY_Q", {"KEY_Q", 16, "Q"}},
    {"KEY_W", {"KEY_W", 17, "W"}},
    {"KEY_E", {"KEY_E", 18, "E"}},
    {"KEY_R", {"KEY_R", 19, "R"}},
    {"KEY_T", {"KEY_T", 20, "T"}},
    {"KEY_Y", {"KEY_Y", 21, "Y"}},
    {"KEY_U", {"KEY_U", 22, "U"}},
    {"KEY_I", {"KEY_I", 23, "I"}},
    {"KEY_O", {"KEY_O", 24, "O"}},
    {"KEY_P", {"KEY_P", 25, "P"}},
    {"KEY_LEFT", {"KEY_LEFTBRACE", 26, "["}},
    {"KEY_RIGHT", {"KEY_RIGHTBRACE", 27, "]"}},
    {"KEY_ENTER", {"KEY_ENTER", 28, "ENTER"}},
    {"KEY_LEFT", {"KEY_LEFTCTRL", 29, "CTRL"}},
    {"KEY_A", {"KEY_A", 30, "A"}},
    {"KEY_S", {"KEY_S", 31, "S"}},
    {"KEY_D", {"KEY_D", 32, "D"}},
    {"KEY_F", {"KEY_F", 33, "F"}},
    {"KEY_G", {"KEY_G", 34, "G"}},
    {"KEY_H", {"KEY_H", 35, "H"}},
    {"KEY_J", {"KEY_J", 36, "J"}},
    {"KEY_K", {"KEY_K", 37, "K"}},
    {"KEY_L", {"KEY_L", 38, "L"}},
    {"KEY_SEMICOLON", {"KEY_SEMICOLON", 39, ";"}},
    {"KEY_APOSTROPHE", {"KEY_APOSTROPHE", 40, "'"}},
    {"KEY_GRAVE", {"KEY_GRAVE", 41, "`"}},
    {"KEY_LEFTSHIFT", {"KEY_LEFTSHIFT", 42, "SHIFT"}},
    {"KEY_BACKSPACE", {"KEY_BACKSLASH", 43, "\\"}},
    {"KEY_Z", {"KEY_Z", 44, "Z"}},
    {"KEY_X", {"KEY_X", 45, "X"}},
    {"KEY_C", {"KEY_C", 46, "C"}},
    {"KEY_V", {"KEY_V", 47, "V"}},
    {"KEY_B", {"KEY_B", 48, "B"}},
    {"KEY_N", {"KEY_N", 49, "N"}},
    {"KEY_M", {"KEY_M", 50, "M"}},
    {"KEY_COMMA", {"KEY_COMMA", 51, ","}},
    {"KEY_DOT", {"KEY_DOT", 52, "."}},
    {"KEY_SLASH", {"KEY_SLASH", 53, "/"}},
    {"KEY_RIGHTSHIFT", {"KEY_RIGHTSHIFT", 54, "SHIFT"}},
    {"KEY_KPASTERISK", {"KEY_KPASTERISK", 55, "*"}},
    {"KEY_LEFTALT", {"KEY_LEFTALT", 56, "ALT"}},
    {"KEY_SPACE", {"KEY_SPACE", 57, "SPACE"}},
    {"KEY_CAPSLOCK", {"KEY_CAPSLOCK", 58, "CAPSLOCK"}},
    {"KEY_F1", {"KEY_F1", 59, "F1"}},
    {"KEY_F2", {"KEY_F2", 60, "F2"}},
    {"KEY_F3", {"KEY_F3", 61, "F3"}},
    {"KEY_F4", {"KEY_F4", 62, "F4"}},
    {"KEY_F5", {"KEY_F5", 63, "F5"}},
    {"KEY_F6", {"KEY_F6", 64, "F6"}},
    {"KEY_F7", {"KEY_F7", 65, "F7"}},
    {"KEY_F8", {"KEY_F8", 66, "F8"}},
    {"KEY_F9", {"KEY_F9", 67, "F9"}},
    {"KEY_F10", {"KEY_F10", 68, "F10"}},
    {"KEY_NUMLOCK", {"KEY_NUMLOCK", 69, "NUMLOCK"}},
    {"KEY_SCROLLOCK", {"KEY_SCROLLLOCK", 70, "SCROLLLOCK"}},
    {"KEY_KP7", {"KEY_KP7", 71, "KP7"}},
    {"KEY_KP8", {"KEY_KP8", 72, "KP8"}},
    {"KEY_KP9", {"KEY_KP9", 73, "KP9"}},
    {"KEY_KPMINUS", {"KEY_KPMINUS", 74, "-"}},
    {"KEY_KP4", {"KEY_KP4", 75, "KP4"}},
    {"KEY_KP5", {"KEY_KP5", 76, "KP5"}},
    {"KEY_KP6", {"KEY_KP6", 77, "KP6"}},
    {"KEY_KPPLUS", {"KEY_KPPLUS", 78, "+"}},
    {"KEY_KP1", {"KEY_KP1", 79, "KP1"}},
    {"KEY_KP2", {"KEY_KP2", 80, "KP2"}},
    {"KEY_KP3", {"KEY_KP3", 81, "KP3"}},
    {"KEY_KP0", {"KEY_KP0", 82, "KP0"}},
    {"KEY_KPDOT", {"KEY_KPDOT", 83, "."}},
};

auto it = keyNameMap.find("KEY_A");
if (it != keyNameMap.end()) {
    const KeyInfo& info = it->second;
    std::cout << "Key Name: " << info.keyName
              << ", Key Code: " << info.keyCode
              << ", Character: " << info.keyChar << std::endl;
}
